### ISSUE TITLE
code usage

### ISSUE THREAD

**Issue by justlovebarbecue** [akshaygadipatil/LayoutGMN-pytorch#1]
Hi there, 
Thanks for providing your code! Could you please provide more details about how to use these scripts and about the data preparation? right now it is not very clear to run these models.

Thanks!

**Comment by berylsheep-up** [comment]
Thanks for the excellent job! Similar request is asked.
Could you provide some data preparation scripts to run these files? Take Rico dataset as example, althogh the code for create graph data is provided, but it is no obvious for turning the original Rico datasets into the loaded files like 
`BoxInfo = pickle.load(open('../data/FP_box_info.pkl', 'rb'))` in 150 line in 0_cal_geometry_feat.py ;
`self.info = pickle.load(open('/gruvi/usr/akshay/1-FPs/7-FP_Metric/GCN_CNN_scripts/data/FP_box_info_list.pkl', 'rb'))
        ` in 60 line in dataloader_triplet.py ;
`UI_data = pickle.load(open("/gruvi/usr/akshay/1-FPs/7-FP_Metric/GCN_CNN_scripts/data/FP_data.p", "rb"))
        ` in 81 line in dataloader_triplet.py , and so on.
Thanks!

**Comment by agp-ka32** [comment]
Hi @berylsheep-up,

The data files, viz, `FP_box_info.pkl`, `FP_box_info_list`, and `FP_data` are later converted to `APN_dict`, which can be obtained from [this link](https://drive.google.com/drive/folders/1Qp94A2NQLdBcgaIEuJDJIffk5NHxIVxH). Note that this has also been mentioned in the README.md file in the root directory of this repository, under `Preparing Layout Graphs`. 

I have also added [this](https://github.com/akshaygadipatil/LayoutGMN-pytorch/tree/main/Triplet_data) folder containing scripts to prepare your own training data. 

Let me know if this helps.

**Comment by agp-ka32** [comment]
Please let me know if this helps.

**Comment by agp-ka32** [comment]
I assume the issue has been resolved. Closing this issue for now.
