### ISSUE TITLE
In addition, could you share your the code of handle the RFPlan dataset?

### ISSUE THREAD

**Issue by gogo03** [akshaygadipatil/LayoutGMN-pytorch#3]
thank you very much

**Comment by agp-ka32** [comment]
Please see my response to your [previous question](https://github.com/akshaygadipatil/LayoutGMN-pytorch/issues/2#issue-1174839068). 

You need to download the RPLAN dataset, and visualize the floorplans there. For now, we do not provide code to visualize the floorplans. We may add that part, but currently we are not looking into that. There are other sources that help you with that, like [this one](https://github.com/zzilch/RPLAN-Toolbox), although that is totally up to the user, as our code is independent of the linked repo.
