### ISSUE TITLE
ask for APN to reproduce on RPLAN

### ISSUE THREAD

**Issue by Ji-Pengliang** [akshaygadipatil/LayoutGMN-pytorch#4]
Hello, fascinated by your impressive work!
Could you provide the APN of floorplan dataset RPLAN? I would be very grateful and much appreciated!

**Comment by gogo03** [comment]
me too.   If we try to generate APN file, it will cost hundreds of hours。

**Comment by agp-ka32** [comment]
Provided the link to download the APN dict. See this issue: https://github.com/akshaygadipatil/LayoutGMN-pytorch/issues/2#issuecomment-1079155550.

Closing this issue.
