### ISSUE TITLE
the question about 0_cal_geometory_feat.py

### ISSUE THREAD

**Issue by gogo03** [akshaygadipatil/LayoutGMN-pytorch#6]
Sorry to bother you again, when I exec 0_cal_geometory_feat.py, it need FP_box_info.pkl, but I cannot find it, could you share this file?
You metioned in https://github.com/akshaygadipatil/LayoutGMN-pytorch/issues/1.  But this file is a APN*48*.pkl.

**Comment by agp-ka32** [comment]
Pickle files have been uploaded to the repo. Check [this](https://github.com/akshaygadipatil/LayoutGMN-pytorch#preparing-layout-graphs).
